#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# BACKUP APP FILES (excluding venv — recreated on restore)
#=================================================
ynh_script_progression --message="Backing up $app files..." --weight=5

ynh_backup --src_path="$install_dir/backend/main.py"
ynh_backup --src_path="$install_dir/backend/requirements.txt"
ynh_backup --src_path="$install_dir/frontend"
ynh_backup --src_path="$install_dir/.env"

#=================================================
# BACKUP DATABASE
#=================================================
ynh_script_progression --message="Backing up database..." --weight=5

ynh_backup --src_path="$data_dir"

#=================================================
# END
#=================================================
ynh_script_progression --message="Backup of $app completed!" --last
