#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression --message="Stopping and removing $app service..." --weight=2

ynh_systemd_action --service_name="$app" --action=stop --log_path=systemd || true
ynh_remove_systemd_config

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Removing NGINX configuration..." --weight=1

ynh_remove_nginx_config

#=================================================
# END
#=================================================
ynh_script_progression --message="Removal of $app completed!" --last
